# Generated by Django 3.1.7 on 2021-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_news', models.CharField(max_length=33, verbose_name='Автор новости')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(blank=True, upload_to='image_news/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Все новости',
            },
        ),
    ]
