# Generated by Django 3.1.7 on 2021-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20210326_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_publiced',
            field=models.BooleanField(default=True, verbose_name='Доступна'),
        ),
    ]
