# Generated by Django 3.1.7 on 2021-04-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20210326_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='image_news/%Y/%m/%d/'),
        ),
    ]
