# Generated by Django 3.1.7 on 2021-04-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Feature_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Особенности товара')),
            ],
            options={
                'verbose_name': 'Особенности товара',
                'verbose_name_plural': 'Особенности товаров',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('warranty', models.FloatField(blank=True, verbose_name='Гарантия(Время)')),
                ('manufacturer_company', models.CharField(blank=True, max_length=48, verbose_name='Компания производитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')),
                ('seller', models.CharField(max_length=48, verbose_name='Продавец')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Shop.category_product', verbose_name='Категория товара')),
                ('features', models.ManyToManyField(blank=True, null=True, to='Shop.Feature_Product', verbose_name='Особенности товара/эксплуатации')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Все товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
