# Generated by Django 3.1.7 on 2021-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=48, verbose_name='Особенности товара/эксплуатации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.FloatField(blank=True, verbose_name='Гарантия(В месяцах)'),
        ),
    ]
