# Generated by Django 3.1.7 on 2021-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210419_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='Shop.Feature_Product', verbose_name='Особенности товара/эксплуатации'),
        ),
    ]
