# Generated by Django 3.1.7 on 2021-04-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, verbose_name='Гарантия(В месяцах)'),
        ),
    ]
