# Generated by Django 3.1.7 on 2021-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20210420_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Выберите аватарку товара'),
        ),
    ]
