# Generated by Django 3.1.7 on 2021-05-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20210503_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_verifed',
        ),
    ]
