# Generated by Django 3.1.7 on 2021-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_remove_product_is_verifed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.CharField(default='chekashovmatvey@gmail.com', max_length=48, verbose_name='E-Mail для связи покупателей с вами'),
        ),
    ]
