# Generated by Django 3.1.7 on 2021-05-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_product_seller_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_buyer', models.CharField(blank=True, max_length=48, verbose_name='Логин покупателя')),
                ('purchased_product_id', models.CharField(blank=True, max_length=48, verbose_name='id товара')),
            ],
        ),
    ]
