# Generated by Django 3.1.7 on 2021-05-22 09:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_auto_20210518_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(max_length=48, verbose_name='Продавец(Будет установлен ваш логин)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, default='Не указанно', verbose_name='Гарантия(В месяцах)'),
        ),
    ]
