# Generated by Django 3.1.7 on 2021-05-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_auto_20210522_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гарантия(В месяцах)'),
        ),
    ]
